import "bootstrap/dist/css/bootstrap.rtl.css";
import "../styles/globals.css";
import type { AppProps } from "next/app";
import { NextPage } from "next";
import Head from "next/head";
import React, { ReactElement, ReactNode } from "react";
import { Dashboard } from "../layouts/dashboard";

type NextPageWithLayout = NextPage & {
  dashboard?: boolean;
  title?: string;
};

type AppPropsWithLayout = AppProps & {
  Component: NextPageWithLayout;
};

export default function MyApp({ Component, pageProps }: AppPropsWithLayout) {
  const title = Component.title ?? "داشبورد استورت آپ";
  let page: ReactNode;
  if (Component.dashboard) {
    page = (
      <Dashboard title={title}>
        <Component {...pageProps} />
      </Dashboard>
    );
  } else {
    page = <Component {...pageProps} />;
  }

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="TODO Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {page}
    </>
  );
}
