import type { NextPage } from "next";
import Head from "next/head";
import React, { ReactElement } from "react";
import { Dashboard } from "../layouts/dashboard";
export default function Index() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>سلام</h1>
    </>
  );
}
